service: shop

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 256
  timeout: 10
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Scan
      Resource: "arn:aws:dynamodb:us-east-1:130956142913:table/product"

plugins:
  - serverless-webpack
  
package:
  individually: true
  
functions:
  getProductsList:
    handler: handlers.getProductsList
    events:
      - http:
          path: /products
          method: get
    environment:
      PRODUCTS_TABLE: product
      STOCK_TABLE: stock

  getProductsById:
    handler: handlers.getProductsById
    events:
      - http:
          path: /products/{productId}
          method: get
    environment:
      PRODUCTS_TABLE: product
      STOCK_TABLE: stock

  createProduct:
    handler: handlers.createProduct
    events:
      - http:
          path: /products
          method: post
    environment:
      PRODUCTS_TABLE: product
      STOCK_TABLE: stock

